tagFormat: "${version}"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  -
    - "@semantic-release/exec"
    - publishCmd: |
        git tag -a -f ${nextRelease.version} ${nextRelease.version} -F CHANGELOG.md
        git push --force origin ${nextRelease.version}
  - "gradle-semantic-release-plugin"
  -
    - "@semantic-release/git"
    - assets:
      - gradle.properties
      - CHANGELOG.md
  -
    - "@semantic-release/exec"
    - publishCmd: |
        ./gradlew publishPluginMavenPublicationToSonatypeRepository || exit 1
  - "@semantic-release/github"
