name: Build, Test and Publish

on:
  pull_request:
    branches: [master, develop]
  push:
    branches: [master, develop]
    tags: [v*]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2

      # Setup Java 1.8 environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Lint check
      - name: Linting checking
        run: ./gradlew ktlintCheck

      # detekt
      - name: Detekt
        run: ./gradlew detekt

      # Build application
      - name: Build
        run: ./gradlew build

      # Test application
      - name: Test
        run: ./gradlew test